In [ ]:
from google.colab import files
uploaded = files.upload()

Saving IT_Support_Tickets.xlsx to IT_Support_Tickets.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("IT_Support_Tickets.xlsx")

df.head()

,Ticket_ID,Created_Date,Resolution_Date,Status,Priority,Ticket_Type,Category,Country,Cluster_ID,Cluster_Name,...,Channel,Description,Tags,Product,Customer_Satisfaction,Escalation_Level,Region,Device_Type,Operating_System,Resolution_Notes
0,TKT00001,2025-04-25 00:00,2025-04-26 08:00,Resolved,Low,Problem,Access,India,1,Cluster_3,...,Chat,Synthetic IT support ticket generated for anal...,security,Office365,1,1,LATAM,Mobile,macOS,Issue resolved after troubleshooting.
1,TKT00002,2025-06-09 06:00,2025-06-09 20:00,Resolved,High,Request,Integration,India,24,Cluster_15,...,Portal,Synthetic IT support ticket generated for anal...,security,ERP,1,0,EMEA,Mobile,Windows,Issue resolved after troubleshooting.
2,TKT00003,2025-08-27 03:00,2025-08-28 15:00,Open,Medium,Request,Bug,Germany,22,Cluster_9,...,Chat,Synthetic IT support ticket generated for anal...,email,Office365,5,1,NaN,Laptop,Linux,Issue resolved after troubleshooting.
3,TKT00004,2025-02-02 10:00,2025-02-03 21:00,Pending,High,Incident,Email,Singapore,21,Cluster_15,...,Chat,Synthetic IT support ticket generated for anal...,security,VPN,3,1,EMEA,Tablet,Windows,Issue resolved after troubleshooting.
4,TKT00005,2025-02-18 03:00,2025-02-21 12:00,In Progress,Low,Request,Access,UAE,17,Cluster_9,...,Chat,Synthetic IT support ticket generated for anal...,vpn,VPN,1,2,EMEA,Laptop,macOS,Issue resolved after troubleshooting.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              10000 non-null  object
 1   Created_Date           10000 non-null  object
 2   Resolution_Date        10000 non-null  object
 3   Status                 10000 non-null  object
 4   Priority               10000 non-null  object
 5   Ticket_Type            10000 non-null  object
 6   Category               10000 non-null  object
 7   Country                10000 non-null  object
 8   Cluster_ID             10000 non-null  int64
 9   Cluster_Name           10000 non-null  object
 10  Similarity_Score       10000 non-null  float64
 11  Similarity_Level       10000 non-null  object
 12  First_Response_Date    10000 non-null  object
 13  Assigned_Agent         10000 non-null  object
 14  Team                   10000 non-null  object
 15  SLA_Status             10000 non-null  object
 16  Reopened               10000 non-null  object
 17  Resolution_Code        10000 non-null  object
 18  Department             10000 non-null  object
 19  Customer_ID            10000 non-null  object
 20  Channel                10000 non-null  object
 21  Description            10000 non-null  object
 22  Tags                   10000 non-null  object
 23  Product                10000 non-null  object
 24  Customer_Satisfaction  10000 non-null  int64
 25  Escalation_Level       10000 non-null  int64
 26  Region                 7570 non-null   object
 27  Device_Type            10000 non-null  object
 28  Operating_System       10000 non-null  object
 29  Resolution_Notes       10000 non-null  object
dtypes: float64(1), int64(3), object(26)
memory usage: 2.3+ MB

In [ ]:
df.dtypes

Ticket_ID                 object
Created_Date              object
Resolution_Date           object
Status                    object
Priority                  object
Ticket_Type               object
Category                  object
Country                   object
Cluster_ID                 int64
Cluster_Name              object
Similarity_Score         float64
Similarity_Level          object
First_Response_Date       object
Assigned_Agent            object
Team                      object
SLA_Status                object
Reopened                  object
Resolution_Code           object
Department                object
Customer_ID               object
Channel                   object
Description               object
Tags                      object
Product                   object
Customer_Satisfaction      int64
Escalation_Level           int64
Region                    object
Device_Type               object
Operating_System          object
Resolution_Notes          object
dtype: object

In [ ]:
df.isnull().sum()

Ticket_ID                   0
Created_Date                0
Resolution_Date             0
Status                      0
Priority                    0
Ticket_Type                 0
Category                    0
Country                     0
Cluster_ID                  0
Cluster_Name                0
Similarity_Score            0
Similarity_Level            0
First_Response_Date         0
Assigned_Agent              0
Team                        0
SLA_Status                  0
Reopened                    0
Resolution_Code             0
Department                  0
Customer_ID                 0
Channel                     0
Description                 0
Tags                        0
Product                     0
Customer_Satisfaction       0
Escalation_Level            0
Region                   2430
Device_Type                 0
Operating_System            0
Resolution_Notes            0
dtype: int64

In [ ]:
df.shape

(10000, 30)

In [ ]:
df["Ticket_Type"].value_counts()

Ticket_Type
Request     3421
Problem     3310
Incident    3269
Name: count, dtype: int64

In [ ]:
df["Priority"].value_counts()

Priority
Medium      2551
Critical    2498
High        2481
Low         2470
Name: count, dtype: int64

In [ ]:
df["Category"].value_counts()

Category
Software       1309
Security       1278
Hardware       1274
Integration    1256
Bug            1236
Access         1228
Email          1213
Network        1206
Name: count, dtype: int64

In [ ]:
df[['Category', 'Ticket_Type']].drop_duplicates().sort_values('Category')

       Category Ticket_Type
0        Access     Problem
4        Access     Request
36       Access    Incident
2           Bug     Request
5           Bug     Problem
14          Bug    Incident
63        Email     Request
3         Email    Incident
51        Email     Problem
31     Hardware    Incident
64     Hardware     Problem
73     Hardware     Request
29  Integration    Incident
6   Integration     Problem
1   Integration     Request
13      Network     Problem
9       Network     Request
30      Network    Incident
17     Security     Request
8      Security    Incident
7      Security     Problem
18     Software     Problem
10     Software    Incident
11     Software     Request

In [ ]:
df["Region"] = df["Region"].fillna("Unknown")

In [ ]:
df["Region"].isnull().sum()

np.int64(0)

In [ ]:
df["Created_Date"] = pd.to_datetime(df["Created_Date"])
df["Resolution_Date"] = pd.to_datetime(df["Resolution_Date"])

In [ ]:
df["Resolution_Duration"] = (
    df["Resolution_Date"] - df["Created_Date"]
).dt.total_seconds() / 3600

In [ ]:
df[["Created_Date", "Resolution_Date", "Resolution_Duration"]].head()

         Created_Date     Resolution_Date  Resolution_Duration
0 2025-04-25 00:00:00 2025-04-26 08:00:00                 32.0
1 2025-06-09 06:00:00 2025-06-09 20:00:00                 14.0
2 2025-08-27 03:00:00 2025-08-28 15:00:00                 36.0
3 2025-02-02 10:00:00 2025-02-03 21:00:00                 35.0
4 2025-02-18 03:00:00 2025-02-21 12:00:00                 81.0

In [ ]:
priority_map = {
    "Low": 1,
    "Medium": 2,
    "High": 3
}

df["Priority_Score"] = df["Priority"].map(priority_map)

In [ ]:
df[["Priority", "Priority_Score"]].head()

  Priority  Priority_Score
0      Low             1.0
1     High             3.0
2   Medium             2.0
3     High             3.0
4      Low             1.0

In [ ]:
df.to_excel("IT_Support_Tickets_Cleaned.xlsx", index=False)